In [6]:
import numpy as np

my_numbers = (8, 12, 16, 24, 4)

my_numbers_mean = 12.8

#subtracting mean from each member of list then squaring. Add each result to get variance
#23.04 + 0.64 + 10.24 + 144 + 64 = 241.92

#Square root variance to get SD
#square root of 241.92 = 15.55 
SD = 241.92





In [20]:
#Exercise 1:
##Now with NUMPY!##

import numpy as np
import math

my_num_array = np.array([8, 12, 16, 24, 4])



def find_SD(num_array):
    """finds the standard deviation from an array of numbers"""
    variances = []
    counter = 0
    meanval = np.mean(num_array)
    print(meanval)
    while len(num_array) > counter:
        variances.append((num_array[counter]-meanval)**2) 
        counter += 1
        print(counter)
    SD = math.sqrt(sum(variances)/len(num_array))
    return SD


#Call SD function
mySD = find_SD(my_num_array)

print(mySD)

12.8
1
2
3
4
5
6.881860213634101


In [24]:
#Excercise 2:
#If some outliers are introduced to the dataset, 
# what will happen to the Standard Deviation? Will it increase, decrease or remain the same?

#Hypothesis: adding outliers will impact the standard deviation
#Null Hyp: adding outliers will not impact SD

my_num_array = np.array([8, 12, 16, 24, 4])
my_num_array2= np.append(my_num_array,[2000,1,1]) # adding outliers

mySD2 = find_SD(my_num_array2)

#Hypothesis proven; SD changes when outliers are introduced. 
# The severity of the change depends on the weight of the outlier.

[   8   12   16   24    4 2000    1    1]
258.25
1
2
3
4
5
6
7
8
658.3609857061701


In [ ]:
#Ex 3
#Suppose the below positively skewed distribution has a median of 30, which of the following statement is true?

#A) Mean is greater than 30
#B) Mean is less than 30
#C) Mode is greater than 30
#D) Mode is less than 30
#E) Both A and D
#F) Both B and C

#E; the mean>30 and the mode<30, as can be observed on the graph plotted in the excercise.


In [18]:
#Ex 4
#what is likely to be the median value 
array_1=[[10, 10, 10, 10, 11, 11, 12, 13, 14 ],
[15, 15, 15, 16, 16, 16, 16, 16, 17, 18, 19, 19],
[20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 23, 23, 23, 24, 24, 24],
[26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 29, 29, 29, 29, 29, 29, 29, 29, 29],
[30, 30, 30, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34],
[35, 35, 35, 37, 37, 37, 37, 39, 39, 39],
[40, 40, 43, 43, 44, 44],
[46, 46, 46, 47, 49],
[52, 53, 54]]
#ISSUE, inhomogenous array, have to use list comprehension to create flattened array

import numpy as np
def find_median(my_arr):
    """flattens inhomogenous arrays and finds median in an array of numbers"""
    flat_array= [element for sublist in my_arr for element in sublist] 
    found_median=np.median(flat_array)
    
    return found_median

check = find_median(array_1)
print(check)

#Median = 27


27.0


In [ ]:
#Ex 5,6,7 no numpy allowed

#5: what is the shape of the distribution?
    #Shape is a tuple containing integers representing the size of each dimension of the array
    #would return something like: (11,24,29,9,0,5,4,6,3,3,3,2,1,1,1,1,2,0)

    
#6: What central frequency statistical method would best represent the center of the data shown?
    #Mode would be the best representation of the center of the data
        #because 29 is most frequent, but due to quanitity of dimensions, the mean would massively misrepresent the center
            #the median and mode would in this case look similar

#7: How many individuals would have a salary of less than 10k?
    #11+24 = 35





In [41]:
#Ex 8:
#We have a set of positive numbers. If a single value of the set is altered what must change?

#A) Mean
#B) Median
#C) Mode
#D) All of these

###MEDIAN
#Proof, median changes or not after a member of array is changed:
test_arr=([[1,4,50,2,78,215,43,12],[1,2]]) #NOTE needed a nested array for median function to work, 
                                                #cba rewriting it because the list comprehension was cool 

og_median = find_median(test_arr)

#changing the index 0 of the first dimension of the test array
test_arr [0][0] = 100
new_median = find_median(test_arr)

print(f"Median of original array: {og_median}")
print(f"New median after changing a number: {new_median}")

#Conclusion: median changes if value is changed


###MEAN
test_arr =np.array([1,4,50,2,78,215,43,12])
meanval = np.mean(test_arr)

test_arr[0] = 120

new_meanval = np.mean(test_arr)

print(f"Mean of original array: {meanval}")
print(f"Mean of changed array: {new_meanval}")

#CONCLUSION
#Mean changes if a single value changes


###MODE
test_arr =np.array([1,4,50,2,78,215,43,12])
modeval = test_arr[int(len(test_arr)/2)] # picks out the central value of the array

test_arr[6] = 120
new_meanval = test_arr[int(len(test_arr)/2)]
print(f"Mode of original array: {modeval}")
print(f"Mode of changed array: {new_meanval}")


#Conclusion: as long as the amount of values in a dimension of an array is consistent, the mean of the dimension wont change


Median of original array: 8.0
New median after changing a number: 27.5
Mean of original array: 50.625
Mean of changed array: 65.5
Mode of original array: 78
Mode of changed array: 78


In [51]:
#Ex 9: The chart shows hourly consultancy rate of 10 people. 
    #  Calculate the standard deviation of the salaries of the 10 employees.

hour_rates = np.array([25,25,25,40,40,35,50,50,50,50])


def find_SD2(this_array):
    """finds standard deviation using a for loop instead of while loop"""
    meanval = np.mean(this_array)
    var_calc = []
    for element in this_array:
        var_calc.append((element-meanval)**2)

    #Add up all the calculation elements and divide them by the length of the array
    total = 0
    for x in var_calc:
        total += x
    
    SD = (total/ (len(this_array)))**0.5
    return SD 

find_SD2(hour_rates) #checked, SD is correct


10.44030650891055

In [ ]:
#Ex 10:  (no numpy)

#Which of the following random variables is discrete?

#A) the length of time a battery lasts #Not exact, therefore not discrete
#B) the number of pens purchased by a student in a year #descrete!
#C) the percentage of cows in a cattle firm that have been vaccinated #Percentages can be reoccuring decimals so not discrete
#D) the distance between a pair of towns #technically, distance can also have reoccuring decimals so also not discrete



In [ ]:
#Exercise 11 (no Numpy)
#Which of the below normal distributions will have the greatest spread?
#mu = mean of the central distribution
#sigma = represents the SD of the data set; "width" of distribution curve

#A) mu=5, sigma =1.5
#B) mu=10, sigma =1.0
#C) mu=5, sigma =1.65  # as this has the greatest sigma, it will have the widest spread
#D) mu=8, sigma =1.2
#E) mu=10, sigma =1.6

###CONCLUSION: C

In [14]:
#Advanced excercises:
#3. Create a null vector of size 10 (★☆☆)
# ex: 3 - `hint: np.zeros`
nullarr = np.zeros(10)
print(nullarr)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
#### 4. How to find the memory size of any array (★☆☆)
#`hint: size, itemsize`
memsize= nullarr.itemsize
print(memsize)


8


In [24]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
#`hint: np.info`
#in command line: python c- "import numpy as np; np.info('np.add')""


Help for np.add not found.


In [51]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#`hint: array[4]`
import numpy as np
null_vec = np.zeros(10)
null_vec[4] = 1
print(null_vec)





[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [36]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
#`hint: arange`
myvec = np.arange(10,50)

print(myvec)



[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [37]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)
#`hint: array[::-1]`
print(myvec[::-1])



[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [55]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#`hint: reshape`

import numpy as np
mymat = np.arange(9).reshape((3,3))
print(mymat)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [56]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#`hint: np.nonzero`
sample_arr = [1,2,0,0,4,0]
nonzeros = np.nonzero(sample_arr)
print(nonzeros)



(array([0, 1, 4], dtype=int64),)


In [60]:
#### 11. Create a 3x3 identity matrix (★☆☆)
#`hint: np.eye`
myidmat = np.eye(3,3)
print(myidmat)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [70]:



#### 12. Create a 3x3x3 array with random values (★☆☆)
#`hint: np.random.random`
my333 = np.random.random((3,3,3))
print(my333)



[[[0.69235969 0.8543645  0.94063818]
  [0.06535833 0.05332337 0.7011381 ]
  [0.19238112 0.54030083 0.33898461]]

 [[0.75121314 0.29874057 0.2306992 ]
  [0.72627842 0.28990764 0.28061215]
  [0.06167918 0.74662566 0.80643363]]

 [[0.09125929 0.71481931 0.39150035]
  [0.14265556 0.19330756 0.18540854]
  [0.81954498 0.76824471 0.96136592]]]


In [72]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
#`hint: min, max`
my10by10 = np.random.random((10,10))
print("This is my10by10",my10by10)
print("This is min:",np.min(my10by10))
print("This is max:",np.max(my10by10))



This is my10by10 [[0.29573386 0.77949972 0.77346533 0.41910674 0.65400613 0.29637548
  0.11003266 0.9879517  0.51411789 0.85212156]
 [0.93140956 0.7359688  0.92888757 0.07811341 0.08597428 0.81035285
  0.3951996  0.66251509 0.81752101 0.63345871]
 [0.02036324 0.46142883 0.67773282 0.79180079 0.90540174 0.71990544
  0.85317498 0.97663405 0.67950099 0.40573851]
 [0.09878978 0.49160445 0.17218839 0.19015105 0.78288357 0.42924732
  0.40296269 0.28514498 0.73323864 0.98124564]
 [0.33622429 0.36143312 0.04579342 0.64815079 0.6591857  0.04757419
  0.36627499 0.69768193 0.82758772 0.36109239]
 [0.74208696 0.79518706 0.30338137 0.23710581 0.9620714  0.6714673
  0.55257314 0.94014105 0.89204565 0.94266567]
 [0.37652475 0.77276304 0.67760252 0.78076421 0.1226459  0.45379289
  0.3020811  0.23186521 0.96211591 0.20785124]
 [0.97755035 0.34537052 0.69836979 0.70183111 0.73694936 0.43163184
  0.78678803 0.81586579 0.87674122 0.19319006]
 [0.2443015  0.41090716 0.12114008 0.37574068 0.04977434 0.91540

In [73]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
#`hint: mean`
meanarr = np.random.random(30)
themean = np.mean(meanarr)
print(themean)





0.4437648719000205


In [87]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
#`hint: array[1:-1, 1:-1]`
my2D = np.ones((10,10))
print(my2D)
my2D[1:-1, 1:-1] = 0
print(my2D)



[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [95]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
#`hint: np.pad`

mybigarr = np.ones((10,10))
print(mybigarr)
paddedarr= np.pad(mybigarr, pad_width= 1, mode = "constant")
print(paddedarr)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [96]:

#### 17. What is the result of the following expression? (★☆☆)
#```python
#0 * np.nan # returns nan, as anything multiplied by a n
#np.nan == np.nan #False, since nan is a float that is not equal to any other float
#np.inf > np.nan #Returns False because it cannot participate in mathematical expressions
#np.nan - np.nan #Returns np.nan because it cannot participate in mathematical expressions
#np.nan in set([np.nan]) #True, as nan is in a set of nan
#0.3 == 3 * 0.1 #True because maths, but in python False. The reason for this discrepancy lies in the way computers 
# represent floating-point numbers, specifically the IEEE 754 standard used by Python. 
# This standard allows for approximate representations of decimal numbers, which can lead to small errors.
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)
#```
#`hint: NaN = not a number, inf = infinity`


nan
False
False
nan
True
False


In [100]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
#`hint: np.diag`
thisarr = np.zeros((5,5))
onesandsuch = [1,2,3,4]
diagonals = np.diag((onesandsuch), -1) #neg for under middle diag, + for above diag
print(diagonals)













[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [102]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
#`hint: array[::2]`
checkerboard = np.zeros((8,8))
checkerboard[1::2,0::2] = 1
checkerboard[0::2,1::2] = 1
print(checkerboard)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [104]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
#`hint: np.unravel_index`
#massivearr = np.arange(6,7,8)
#hundth_el = np.unravel_index(massivearr, 3, "C")
#print(hundth_el) #couldnt get it

print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)
